services:
  hoster:
    image: dvdarias/docker-hoster
    container_name: hoster
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
  kopia:
    image: kopia/kopia:latest
    hostname: CHANGEME
    container_name: Kopia
    restart: always
    ports:
      - 51515:51515
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=dean
      - --server-password=CHANGEME
    environment:
      # Set repository password
      KOPIA_PASSWORD: "CHANGEME"
    volumes:
      # Mount local folders needed by kopia
      - ./kopia/config:/app/config
      - ./kopia/cache:/app/cache
      - ./kopia/logs:/app/logs
      # Mount local folders to backup
      - /home/dean/code:/data/code
      # Mount repository location
      - ./kopia/repo:/repository
      # Mount path for browsing mounted snaphots
      #- ./kopia/tmp:/tmp:shared
